
/**************************************************************
 *	
 *	clock, 8 bit, 11025Hz,
 *	1 channel, 88092 bytes/channel
 *	Total Size: 1 * 88092 + 4 (header) = 88136 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M03 - Copy\clock.wav
 *	Time-stamp: Wed Apr 17 22:39:24 2019
 *	
 **************************************************************/

#ifndef __CLOCKH__
#define __CLOCKH__

#define CLOCKFREQ 11025
#define CLOCKLEN 88092

extern const unsigned char clock[88092];

#endif /* __CLOCKH__ */
