
/**************************************************************
 *	
 *	explosion, 8 bit, 44100Hz,
 *	1 channel, 461604 bytes/channel
 *	Total Size: 1 * 461604 + 4 (header) = 461648 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M05 - Final\explosion.wav
 *	Time-stamp: Sat Apr 20 18:41:29 2019
 *	
 **************************************************************/

#ifndef __EXPLOSIONH__
#define __EXPLOSIONH__

#define EXPLOSIONFREQ 44100
#define EXPLOSIONLEN 461604

extern const unsigned char explosion[461604];

#endif /* __EXPLOSIONH__ */
