
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 2280960 bytes/channel
 *	Total Size: 1 * 2280960 + 4 (header) = 2281004 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M03 - Copy\gameMusic.wav
 *	Time-stamp: Wed Apr 17 20:06:07 2019
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 2280960

extern const unsigned char gameMusic[2280960];

#endif /* __GAMEMUSICH__ */
