
/**************************************************************
 *	
 *	instructionMusic, 8 bit, 11025Hz,
 *	1 channel, 1723728 bytes/channel
 *	Total Size: 1 * 1723728 + 4 (header) = 1723772 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M03 - Copy\instructionMusic.wav
 *	Time-stamp: Wed Apr 17 23:48:15 2019
 *	
 **************************************************************/

#ifndef __INSTRUCTIONMUSICH__
#define __INSTRUCTIONMUSICH__

#define INSTRUCTIONMUSICFREQ 11025
#define INSTRUCTIONMUSICLEN 1723728

extern const unsigned char instructionMusic[1723728];

#endif /* __INSTRUCTIONMUSICH__ */
