
/**************************************************************
 *	
 *	jetpack, 8 bit, 44100Hz,
 *	1 channel, 155750 bytes/channel
 *	Total Size: 1 * 155750 + 4 (header) = 155794 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M05 - Final - Rotation, Timer, Screens\jetpack.wav
 *	Time-stamp: Thu Apr 25 16:24:31 2019
 *	
 **************************************************************/

#ifndef __JETPACKH__
#define __JETPACKH__

#define JETPACKFREQ 44100
#define JETPACKLEN 155750

extern const unsigned char jetpack[155750];

#endif /* __JETPACKH__ */
