
/**************************************************************
 *	
 *	laser, 8 bit, 44100Hz,
 *	1 channel, 95088 bytes/channel
 *	Total Size: 1 * 95088 + 4 (header) = 95132 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M03 - Copy\laser.wav
 *	Time-stamp: Wed Apr 17 22:32:19 2019
 *	
 **************************************************************/

#ifndef __LASERH__
#define __LASERH__

#define LASERFREQ 44100
#define LASERLEN 95088

extern const unsigned char laser[95088];

#endif /* __LASERH__ */
