
/**************************************************************
 *	
 *	lose, 8 bit, 11025Hz,
 *	1 channel, 38846 bytes/channel
 *	Total Size: 1 * 38846 + 4 (header) = 38890 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M05 - Final\lose.wav
 *	Time-stamp: Sat Apr 20 18:46:27 2019
 *	
 **************************************************************/

#ifndef __LOSEH__
#define __LOSEH__

#define LOSEFREQ 11025
#define LOSELEN 38846

extern const unsigned char lose[38846];

#endif /* __LOSEH__ */
