
/**************************************************************
 *	
 *	pause, 8 bit, 11025Hz,
 *	1 channel, 671744 bytes/channel
 *	Total Size: 1 * 671744 + 4 (header) = 671788 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M03 - Copy\pause.wav
 *	Time-stamp: Thu Apr 18 03:13:56 2019
 *	
 **************************************************************/

#ifndef __PAUSEH__
#define __PAUSEH__

#define PAUSEFREQ 11025
#define PAUSELEN 671744

extern const unsigned char pause[671744];

#endif /* __PAUSEH__ */
