
/**************************************************************
 *	
 *	startMusic, 8 bit, 11025Hz,
 *	1 channel, 844032 bytes/channel
 *	Total Size: 1 * 844032 + 4 (header) = 844076 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M03 - Copy\startMusic.wav
 *	Time-stamp: Thu Apr 18 00:42:35 2019
 *	
 **************************************************************/

#ifndef __STARTMUSICH__
#define __STARTMUSICH__

#define STARTMUSICFREQ 11025
#define STARTMUSICLEN 844032

extern const unsigned char startMusic[844032];

#endif /* __STARTMUSICH__ */
