
/**************************************************************
 *	
 *	win, 8 bit, 11025Hz,
 *	1 channel, 70813 bytes/channel
 *	Total Size: 1 * 70813 + 4 (header) = 70857 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Tiana\Documents\School\Spring2019\CS 2261\M05 - Final - Rotation\win.wav
 *	Time-stamp: Mon Apr 22 16:50:53 2019
 *	
 **************************************************************/

#ifndef __WINH__
#define __WINH__

#define WINFREQ 11025
#define WINLEN 70813

extern const unsigned char win[70813];

#endif /* __WINH__ */
